import type { Product, Automobile, Tractor, ElectricBike } from '@/types/product'

// ---------------------------------------------------------------------------
// Automobiles (14)
// ---------------------------------------------------------------------------

export const automobiles: Automobile[] = [
  {
    id: 'auto-001',
    slug: 'toyota-hilux-2022',
    category: 'automobile',
    name: 'Toyota Hilux 2.8 GD-6',
    brand: 'Toyota',
    model: 'Hilux',
    year: 2022,
    price: 28000,
    condition: 'Excellent',
    description:
      'Rugged and dependable, this Toyota Hilux 2.8 GD-6 is built for both highway cruising and off-road adventures. Low mileage, full service history, and a powerful turbo-diesel engine make it the ideal workhorse for any terrain.',
    features: [
      'Turbo-diesel engine',
      'Rear diff-lock',
      'Touchscreen infotainment',
      'Cruise control',
      'Tow bar fitted',
      'Bedliner',
    ],
    imageAlt:
      'White 2022 Toyota Hilux double-cab pickup truck parked on a dirt trail with mountains in the background',
    imagePlaceholder: '/images/placeholders/automobile.svg',
    bodyType: 'Truck',
    mileage: 34000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    engineSize: '2.8L',
  },
  {
    id: 'auto-002',
    slug: 'toyota-land-cruiser-2021',
    category: 'automobile',
    name: 'Toyota Land Cruiser Prado VX',
    brand: 'Toyota',
    model: 'Land Cruiser',
    year: 2021,
    price: 45000,
    condition: 'Excellent',
    description:
      'A flagship SUV renowned for its legendary off-road capability and luxurious cabin. This Land Cruiser Prado VX features leather seats, advanced terrain management, and a proven 4.0L V6 engine.',
    features: [
      'Full-time 4WD',
      'Leather interior',
      'Multi-terrain select',
      'Kinetic dynamic suspension',
      'Cooled seats',
      'Sunroof',
    ],
    imageAlt:
      'Silver 2021 Toyota Land Cruiser Prado VX SUV on a paved road with lush green scenery behind it',
    imagePlaceholder: '/images/placeholders/automobile.svg',
    bodyType: 'SUV',
    mileage: 42000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    engineSize: '4.0L',
  },
  {
    id: 'auto-003',
    slug: 'toyota-corolla-2023',
    category: 'automobile',
    name: 'Toyota Corolla XSE Hybrid',
    brand: 'Toyota',
    model: 'Corolla',
    year: 2023,
    price: 22000,
    condition: 'Excellent',
    description:
      'Fuel-efficient and packed with modern tech, the Corolla XSE Hybrid delivers impressive city and highway economy without sacrificing driving enjoyment. Ideal for daily commuting and long-distance travel alike.',
    features: [
      'Hybrid powertrain',
      'Toyota Safety Sense 3.0',
      'Wireless Apple CarPlay',
      'LED headlights',
      'Adaptive cruise control',
      'Keyless entry',
    ],
    imageAlt:
      'Red 2023 Toyota Corolla XSE Hybrid sedan parked in front of a modern office building at sunset',
    imagePlaceholder: '/images/placeholders/automobile.svg',
    bodyType: 'Sedan',
    mileage: 12000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    engineSize: '1.8L',
  },
  {
    id: 'auto-004',
    slug: 'toyota-camry-2020',
    category: 'automobile',
    name: 'Toyota Camry SE',
    brand: 'Toyota',
    model: 'Camry',
    year: 2020,
    price: 18500,
    condition: 'Good',
    description:
      'A reliable mid-size sedan with a sporty edge. The Camry SE offers responsive handling, a comfortable ride, and outstanding fuel economy. Well-maintained with complete service records.',
    features: [
      'Sport-tuned suspension',
      '8-inch touchscreen',
      'Dual-zone climate control',
      'Rear camera',
      'Lane departure alert',
      'Bluetooth connectivity',
    ],
    imageAlt:
      'Black 2020 Toyota Camry SE sedan driving on a suburban highway with autumn trees lining the road',
    imagePlaceholder: '/images/placeholders/automobile.svg',
    bodyType: 'Sedan',
    mileage: 58000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    engineSize: '2.5L',
  },
  {
    id: 'auto-005',
    slug: 'honda-crv-2022',
    category: 'automobile',
    name: 'Honda CR-V EX-L',
    brand: 'Honda',
    model: 'CR-V',
    year: 2022,
    price: 27500,
    condition: 'Excellent',
    description:
      'Spacious, safe, and efficient, the Honda CR-V EX-L is one of the best-selling compact SUVs worldwide. This example comes with leather seats, Honda Sensing safety suite, and a turbocharged engine.',
    features: [
      'Turbocharged engine',
      'Honda Sensing suite',
      'Leather-trimmed seats',
      'Power tailgate',
      'Heated front seats',
      'Wireless phone charger',
    ],
    imageAlt:
      'Blue 2022 Honda CR-V EX-L compact SUV parked at a scenic overlook with a valley view in the background',
    imagePlaceholder: '/images/placeholders/automobile.svg',
    bodyType: 'SUV',
    mileage: 26000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    engineSize: '1.5L Turbo',
  },
  {
    id: 'auto-006',
    slug: 'honda-civic-2023',
    category: 'automobile',
    name: 'Honda Civic Sport',
    brand: 'Honda',
    model: 'Civic',
    year: 2023,
    price: 21000,
    condition: 'Excellent',
    description:
      'The 11th-generation Civic Sport combines a sharp, modern design with a fun-to-drive turbo engine and a refined interior. Low mileage, one owner, and loaded with standard safety tech.',
    features: [
      'Turbocharged 1.5L engine',
      'Sport pedals',
      '9-inch touchscreen',
      'Honda Sensing',
      'Remote start',
      'LED fog lights',
    ],
    imageAlt:
      'Grey 2023 Honda Civic Sport hatchback in a well-lit showroom with reflective floor surfaces',
    imagePlaceholder: '/images/placeholders/automobile.svg',
    bodyType: 'Hatchback',
    mileage: 9500,
    fuelType: 'Petrol',
    transmission: 'Manual',
    engineSize: '1.5L Turbo',
  },
  {
    id: 'auto-007',
    slug: 'nissan-xtrail-2021',
    category: 'automobile',
    name: 'Nissan X-Trail Tekna',
    brand: 'Nissan',
    model: 'X-Trail',
    year: 2021,
    price: 24000,
    condition: 'Good',
    description:
      'A versatile family SUV with seven seats and intelligent 4WD. The X-Trail Tekna comes with a panoramic sunroof, ProPILOT assist, and quilted leather seats for a premium experience.',
    features: [
      'ProPILOT Assist',
      'Panoramic sunroof',
      'Quilted leather seats',
      'Around-view monitor',
      '7-seat configuration',
      'Intelligent 4WD',
    ],
    imageAlt:
      'Dark green 2021 Nissan X-Trail Tekna SUV on a countryside road surrounded by rolling farmland',
    imagePlaceholder: '/images/placeholders/automobile.svg',
    bodyType: 'SUV',
    mileage: 47000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    engineSize: '2.5L',
  },
  {
    id: 'auto-008',
    slug: 'nissan-patrol-2019',
    category: 'automobile',
    name: 'Nissan Patrol V8 Ti-L',
    brand: 'Nissan',
    model: 'Patrol',
    year: 2019,
    price: 38000,
    condition: 'Good',
    description:
      'A commanding full-size SUV with a potent V8 engine and room for the whole family. The Patrol Ti-L delivers unmatched luxury on the road and unstoppable capability off it.',
    features: [
      '5.6L V8 engine',
      'Hydraulic body motion control',
      '8-inch dual screens',
      'Leather seats',
      'BOSE sound system',
      'Intelligent rear-view mirror',
    ],
    imageAlt:
      'Pearl white 2019 Nissan Patrol V8 Ti-L full-size SUV parked on desert sand dunes during golden hour',
    imagePlaceholder: '/images/placeholders/automobile.svg',
    bodyType: 'SUV',
    mileage: 72000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    engineSize: '5.6L',
  },
  {
    id: 'auto-009',
    slug: 'mercedes-sprinter-2020',
    category: 'automobile',
    name: 'Mercedes-Benz Sprinter 314 CDI',
    brand: 'Mercedes-Benz',
    model: 'Sprinter',
    year: 2020,
    price: 32000,
    condition: 'Good',
    description:
      'A versatile commercial van offering exceptional cargo capacity, a smooth turbo-diesel drivetrain, and Mercedes-Benz build quality. Perfect for delivery fleets, tradespeople, or camper conversions.',
    features: [
      'High-roof long-wheelbase',
      'MBUX infotainment',
      'Active brake assist',
      'Crosswind assist',
      'Rear parking sensors',
      'Load-securing rails',
    ],
    imageAlt:
      'White 2020 Mercedes-Benz Sprinter 314 CDI high-roof van on a loading dock at a commercial warehouse',
    imagePlaceholder: '/images/placeholders/automobile.svg',
    bodyType: 'Van',
    mileage: 63000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    engineSize: '2.1L',
  },
  {
    id: 'auto-010',
    slug: 'mercedes-c-class-2022',
    category: 'automobile',
    name: 'Mercedes-Benz C 300 AMG Line',
    brand: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2022,
    price: 42000,
    condition: 'Excellent',
    description:
      'Elegance meets performance in this C 300 AMG Line. Featuring a punchy turbocharged engine, AMG styling, and a tech-laden interior with the latest MBUX system and ambient lighting.',
    features: [
      'AMG body kit',
      'MBUX with 11.9-inch display',
      'Burmester surround sound',
      'Digital instrument cluster',
      '64-colour ambient lighting',
      'Heated steering wheel',
    ],
    imageAlt:
      'Obsidian black 2022 Mercedes-Benz C 300 AMG Line sedan on a rain-slicked city street at night with reflections',
    imagePlaceholder: '/images/placeholders/automobile.svg',
    bodyType: 'Sedan',
    mileage: 18000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    engineSize: '2.0L Turbo',
  },
  {
    id: 'auto-011',
    slug: 'bmw-x3-2021',
    category: 'automobile',
    name: 'BMW X3 xDrive30i M Sport',
    brand: 'BMW',
    model: 'X3',
    year: 2021,
    price: 36000,
    condition: 'Excellent',
    description:
      'A sporty premium SUV blending practicality with driving excitement. The X3 xDrive30i M Sport features all-wheel drive, M Sport suspension, and a luxurious Vernasca leather cabin.',
    features: [
      'M Sport package',
      'xDrive all-wheel drive',
      'Live cockpit professional',
      'Vernasca leather',
      'Panoramic glass roof',
      'Harman Kardon audio',
    ],
    imageAlt:
      'Phytonic blue 2021 BMW X3 xDrive30i M Sport SUV driving through a winding forest road with dappled sunlight',
    imagePlaceholder: '/images/placeholders/automobile.svg',
    bodyType: 'SUV',
    mileage: 31000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    engineSize: '2.0L Turbo',
  },
  {
    id: 'auto-012',
    slug: 'volkswagen-amarok-2022',
    category: 'automobile',
    name: 'Volkswagen Amarok V6 Aventura',
    brand: 'Volkswagen',
    model: 'Amarok',
    year: 2022,
    price: 35000,
    condition: 'Excellent',
    description:
      'The Amarok V6 Aventura combines workhorse utility with premium refinement. Its powerful V6 turbo-diesel delivers impressive towing capability while the Aventura trim adds leather, chrome accents, and advanced tech.',
    features: [
      '3.0L V6 TDI engine',
      'Permanent 4MOTION AWD',
      'Nappa leather seats',
      'Vienna wood trim',
      '8-speed automatic',
      'Trailer stability assist',
    ],
    imageAlt:
      'Canyon brown 2022 Volkswagen Amarok V6 Aventura pickup truck towing a boat trailer beside a lake',
    imagePlaceholder: '/images/placeholders/automobile.svg',
    bodyType: 'Truck',
    mileage: 22000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    engineSize: '3.0L V6',
  },
  {
    id: 'auto-013',
    slug: 'volkswagen-golf-2023',
    category: 'automobile',
    name: 'Volkswagen Golf 8 R-Line',
    brand: 'Volkswagen',
    model: 'Golf',
    year: 2023,
    price: 25000,
    condition: 'Excellent',
    description:
      'The Golf 8 R-Line pairs timeless hatchback practicality with sporty R-Line aesthetics. Turbocharged performance, a digital cockpit, and Volkswagens latest driver-assistance systems come standard.',
    features: [
      'R-Line exterior styling',
      'Digital cockpit Pro',
      'IQ.DRIVE assistance',
      'Adaptive chassis control',
      'Wireless App-Connect',
      'Dynamic turn signals',
    ],
    imageAlt:
      'Moonstone grey 2023 Volkswagen Golf 8 R-Line hatchback parked on a cobblestone European city street',
    imagePlaceholder: '/images/placeholders/automobile.svg',
    bodyType: 'Hatchback',
    mileage: 8000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    engineSize: '1.4L TSI',
  },
  {
    id: 'auto-014',
    slug: 'volkswagen-transporter-2018',
    category: 'automobile',
    name: 'Volkswagen Transporter T6 Kombi',
    brand: 'Volkswagen',
    model: 'Transporter',
    year: 2018,
    price: 3000,
    condition: 'Fair',
    description:
      'A practical and iconic people-mover suitable for both commercial and passenger use. This T6 Kombi seats up to nine, features a proven turbo-diesel engine, and offers flexible seating configurations.',
    features: [
      '9-seat configuration',
      'Sliding side doors',
      'Rear air conditioning',
      'Bluetooth audio',
      'Engine immobiliser',
      'Heavy-duty suspension',
    ],
    imageAlt:
      'White 2018 Volkswagen Transporter T6 Kombi minivan parked outside a rural guesthouse with green hedges',
    imagePlaceholder: '/images/placeholders/automobile.svg',
    bodyType: 'Van',
    mileage: 145000,
    fuelType: 'Diesel',
    transmission: 'Manual',
    engineSize: '2.0L TDI',
  },
]

// ---------------------------------------------------------------------------
// Farm Tractors (6)
// ---------------------------------------------------------------------------

export const tractors: Tractor[] = [
  {
    id: 'tractor-001',
    slug: 'john-deere-5075e-2021',
    category: 'tractor',
    name: 'John Deere 5075E Utility Tractor',
    brand: 'John Deere',
    model: '5075E',
    year: 2021,
    price: 28000,
    condition: 'Excellent',
    description:
      'A versatile utility tractor built for livestock operations, hay production, and property maintenance. The 5075E delivers 75 HP through a proven PowerTech engine with excellent fuel efficiency and low maintenance costs.',
    features: [
      'PowerTech diesel engine',
      '9F/3R SyncShuttle transmission',
      'Independent mid and rear PTO',
      'Foldable ROPS',
      'Ergonomic operator station',
      'Easy-access service points',
    ],
    imageAlt:
      'Green and yellow 2021 John Deere 5075E utility tractor ploughing a brown field on a sunny day',
    imagePlaceholder: '/images/placeholders/tractor.svg',
    horsepower: 75,
    hoursUsed: 820,
    driveType: '4WD',
    ptoType: '540 RPM',
    liftCapacity: '2,070 kg',
  },
  {
    id: 'tractor-002',
    slug: 'kubota-m7060-2020',
    category: 'tractor',
    name: 'Kubota M7060 Premium Tractor',
    brand: 'Kubota',
    model: 'M7060',
    year: 2020,
    price: 32000,
    condition: 'Good',
    description:
      'Kubota reliability meets premium comfort. The M7060 is equipped with a spacious climate-controlled cab, powerful hydraulics, and a fuel-efficient 4-cylinder diesel engine suited for mixed farming operations.',
    features: [
      '4-cylinder Kubota diesel',
      'Climate-controlled cab',
      'Power steering',
      'Rear and mid PTO',
      'Three-point hitch Cat II',
      'Tilt steering column',
    ],
    imageAlt:
      'Orange 2020 Kubota M7060 tractor with enclosed cab working in a green crop field under overcast skies',
    imagePlaceholder: '/images/placeholders/tractor.svg',
    horsepower: 71,
    hoursUsed: 1450,
    driveType: '4WD',
    ptoType: '540/540E RPM',
    liftCapacity: '2,500 kg',
  },
  {
    id: 'tractor-003',
    slug: 'massey-ferguson-4707-2019',
    category: 'tractor',
    name: 'Massey Ferguson 4707 Global Series',
    brand: 'Massey Ferguson',
    model: '4707',
    year: 2019,
    price: 25000,
    condition: 'Good',
    description:
      'A robust and straightforward tractor designed for African and developing-market conditions. The MF 4707 offers high ground clearance, a simple mechanical drivetrain, and easy-to-service AGCO Power engine.',
    features: [
      'AGCO Power 3-cylinder engine',
      '12F/12R transmission',
      'High ground clearance',
      'Mechanical shuttle',
      'Wet disc brakes',
      'Front weight bracket',
    ],
    imageAlt:
      'Red and grey 2019 Massey Ferguson 4707 tractor parked beside a barn with stacked hay bales in the foreground',
    imagePlaceholder: '/images/placeholders/tractor.svg',
    horsepower: 75,
    hoursUsed: 2100,
    driveType: '4WD',
    ptoType: '540 RPM',
    liftCapacity: '2,200 kg',
  },
  {
    id: 'tractor-004',
    slug: 'new-holland-t4-75-2022',
    category: 'tractor',
    name: 'New Holland T4.75 Powerstar',
    brand: 'New Holland',
    model: 'T4.75',
    year: 2022,
    price: 30000,
    condition: 'Excellent',
    description:
      'Compact yet powerful, the T4.75 Powerstar is perfect for mixed farming, vineyard work, and municipal tasks. Its tight turning radius and excellent visibility make it nimble in confined spaces.',
    features: [
      'F5C Tier 4B engine',
      '8x8 Dual Command transmission',
      'Flat-deck platform',
      'Electrohydraulic PTO engagement',
      'Excellent 360-degree visibility',
      'Optional front loader ready',
    ],
    imageAlt:
      'Blue and black 2022 New Holland T4.75 Powerstar tractor on a vineyard path between rows of grapevines',
    imagePlaceholder: '/images/placeholders/tractor.svg',
    horsepower: 75,
    hoursUsed: 560,
    driveType: '4WD',
    ptoType: '540/540E RPM',
    liftCapacity: '2,300 kg',
  },
  {
    id: 'tractor-005',
    slug: 'john-deere-6120m-2020',
    category: 'tractor',
    name: 'John Deere 6120M Row-Crop Tractor',
    brand: 'John Deere',
    model: '6120M',
    year: 2020,
    price: 35000,
    condition: 'Good',
    description:
      'The 6120M is a powerful row-crop tractor engineered for demanding arable operations. It features John Deere PowrQuad Plus transmission, CommandCenter display, and a high-capacity hydraulic system for maximum productivity.',
    features: [
      'PowrQuad Plus 24F/24R transmission',
      'CommandCenter 4200 display',
      'Triple-link suspension',
      'High-flow hydraulics',
      'AutoTrac ready',
      'Premium cab with air ride seat',
    ],
    imageAlt:
      'Green 2020 John Deere 6120M row-crop tractor pulling a disc harrow across a large open field at sunrise',
    imagePlaceholder: '/images/placeholders/tractor.svg',
    horsepower: 120,
    hoursUsed: 1800,
    driveType: '4WD',
    ptoType: '540/540E/1000 RPM',
    liftCapacity: '4,400 kg',
  },
  {
    id: 'tractor-006',
    slug: 'kubota-l3901-2021',
    category: 'tractor',
    name: 'Kubota L3901 Compact Tractor',
    brand: 'Kubota',
    model: 'L3901',
    year: 2021,
    price: 8000,
    condition: 'Fair',
    description:
      'A compact tractor ideal for hobby farms, landscaping, and light-duty tasks. The L3901 punches above its weight with a reliable Kubota diesel, gear-drive transmission, and excellent loader compatibility.',
    features: [
      '3-cylinder Kubota diesel',
      'Gear-drive 8F/4R transmission',
      'Category I 3-point hitch',
      'Front loader compatible',
      'Hydrostatic power steering',
      'Foldable ROPS',
    ],
    imageAlt:
      'Orange 2021 Kubota L3901 compact tractor with front loader bucket on a small hobby farm with wooden fences',
    imagePlaceholder: '/images/placeholders/tractor.svg',
    horsepower: 37,
    hoursUsed: 3200,
    driveType: '4WD',
    ptoType: '540 RPM',
    liftCapacity: '930 kg',
  },
]

// ---------------------------------------------------------------------------
// Electric Bikes (6)
// ---------------------------------------------------------------------------

export const electricBikes: ElectricBike[] = [
  {
    id: 'ebike-001',
    slug: 'voltride-metro-city-ebike-2024',
    category: 'electric-bike',
    name: 'VoltRide Metro City E-Bike',
    brand: 'VoltRide',
    model: 'Metro',
    year: 2024,
    price: 1200,
    condition: 'Excellent',
    description:
      'A sleek city commuter e-bike designed for smooth urban rides. The VoltRide Metro features a lightweight aluminium frame, integrated LED lights, and a whisper-quiet hub motor that makes daily commutes effortless.',
    features: [
      'Lightweight aluminium frame',
      'Integrated front and rear LED lights',
      'Shimano 7-speed drivetrain',
      'LCD display with speedometer',
      'Fender and rear rack included',
      'Puncture-resistant tyres',
    ],
    imageAlt:
      'Matte black 2024 VoltRide Metro city electric bike leaning against a bike rack on a sunlit urban sidewalk',
    imagePlaceholder: '/images/placeholders/electric-bike.svg',
    motorPower: 350,
    batteryCapacity: '36V 13Ah (468Wh)',
    range: 65,
    topSpeed: 25,
    chargeTime: '4-5 hours',
    bikeType: 'City',
  },
  {
    id: 'ebike-002',
    slug: 'trailblazer-summit-mountain-ebike-2023',
    category: 'electric-bike',
    name: 'TrailBlazer Summit Mountain E-Bike',
    brand: 'TrailBlazer',
    model: 'Summit',
    year: 2023,
    price: 3200,
    condition: 'Excellent',
    description:
      'Conquer any trail with the TrailBlazer Summit. Built for rugged mountain terrain, this e-bike features full suspension, a powerful mid-drive motor, and hydraulic disc brakes for ultimate control on steep descents.',
    features: [
      'Full suspension (150mm travel)',
      'Shimano hydraulic disc brakes',
      'Mid-drive Bafang motor',
      'Shimano Deore 10-speed',
      'Dropper seatpost',
      'Reinforced alloy rims',
    ],
    imageAlt:
      'Green and black 2023 TrailBlazer Summit full-suspension electric mountain bike on a rocky forest trail',
    imagePlaceholder: '/images/placeholders/electric-bike.svg',
    motorPower: 750,
    batteryCapacity: '48V 17.5Ah (840Wh)',
    range: 80,
    topSpeed: 45,
    chargeTime: '5-6 hours',
    bikeType: 'Mountain',
  },
  {
    id: 'ebike-003',
    slug: 'cargopro-hauler-500-ebike-2023',
    category: 'electric-bike',
    name: 'CargoPro Hauler 500 E-Bike',
    brand: 'CargoPro',
    model: 'Hauler 500',
    year: 2023,
    price: 4500,
    condition: 'Good',
    description:
      'The ultimate cargo e-bike for families and small businesses. The Hauler 500 features an extended rear rack rated for 80 kg, a low step-through frame, and a powerful motor that handles heavy loads with ease.',
    features: [
      'Extended rear cargo deck (80 kg rated)',
      'Low step-through frame',
      'Dual kickstand',
      'Hydraulic disc brakes',
      'Front cargo basket option',
      'Child seat compatible',
    ],
    imageAlt:
      'Dark blue 2023 CargoPro Hauler 500 cargo electric bike loaded with grocery bags parked outside a market',
    imagePlaceholder: '/images/placeholders/electric-bike.svg',
    motorPower: 500,
    batteryCapacity: '48V 20Ah (960Wh)',
    range: 70,
    topSpeed: 25,
    chargeTime: '6-7 hours',
    bikeType: 'Cargo',
  },
  {
    id: 'ebike-004',
    slug: 'fatmax-dune-rider-ebike-2024',
    category: 'electric-bike',
    name: 'FatMax Dune Rider Fat Tire E-Bike',
    brand: 'FatMax',
    model: 'Dune Rider',
    year: 2024,
    price: 1800,
    condition: 'Excellent',
    description:
      'Go anywhere on the FatMax Dune Rider. Oversized 4-inch fat tyres provide exceptional grip on sand, snow, and gravel, while the powerful rear hub motor delivers effortless acceleration in any conditions.',
    features: [
      '4-inch fat tyres',
      'Front suspension fork',
      'Shimano 7-speed',
      'Half-twist throttle',
      'Colour LCD display',
      'USB charging port on battery',
    ],
    imageAlt:
      'Military green 2024 FatMax Dune Rider fat tire electric bike riding across a sandy beach at low tide',
    imagePlaceholder: '/images/placeholders/electric-bike.svg',
    motorPower: 750,
    batteryCapacity: '48V 15Ah (720Wh)',
    range: 60,
    topSpeed: 40,
    chargeTime: '5-6 hours',
    bikeType: 'Fat Tire',
  },
  {
    id: 'ebike-005',
    slug: 'urbanfold-compact-ebike-2023',
    category: 'electric-bike',
    name: 'UrbanFold Compact Folding E-Bike',
    brand: 'UrbanFold',
    model: 'Compact',
    year: 2023,
    price: 800,
    condition: 'Good',
    description:
      'Perfect for multi-modal commuters, the UrbanFold Compact folds in seconds and fits under a desk or in a car boot. Despite its small size, it delivers a comfortable and zippy ride around the city.',
    features: [
      'Quick-fold mechanism',
      '16-inch wheels',
      'Single-speed drivetrain',
      'Rear rack included',
      'Compact LED headlight',
      'Weighs only 18 kg',
    ],
    imageAlt:
      'White 2023 UrbanFold Compact folding electric bike partially folded next to a train platform bench',
    imagePlaceholder: '/images/placeholders/electric-bike.svg',
    motorPower: 250,
    batteryCapacity: '36V 10Ah (360Wh)',
    range: 45,
    topSpeed: 25,
    chargeTime: '3-4 hours',
    bikeType: 'Folding',
  },
  {
    id: 'ebike-006',
    slug: 'ecoride-city-cruiser-ebike-2024',
    category: 'electric-bike',
    name: 'EcoRide City Cruiser E-Bike',
    brand: 'EcoRide',
    model: 'City Cruiser',
    year: 2024,
    price: 1500,
    condition: 'Excellent',
    description:
      'Cruise the city in style on the EcoRide City Cruiser. A comfortable upright riding position, smooth belt drive, and a long-range battery make this the perfect everyday commuter for riders who value comfort.',
    features: [
      'Gates carbon belt drive',
      'Upright riding geometry',
      'Integrated rear hub motor',
      'Hydraulic disc brakes',
      'Mudguards and chain guard',
      'Adjustable handlebar stem',
    ],
    imageAlt:
      'Teal 2024 EcoRide City Cruiser electric bike with step-through frame parked beside a canal with trees',
    imagePlaceholder: '/images/placeholders/electric-bike.svg',
    motorPower: 350,
    batteryCapacity: '36V 14Ah (504Wh)',
    range: 75,
    topSpeed: 25,
    chargeTime: '4-5 hours',
    bikeType: 'City',
  },
]

// ---------------------------------------------------------------------------
// Combined catalogue
// ---------------------------------------------------------------------------

export const allProducts: Product[] = [
  ...automobiles,
  ...tractors,
  ...electricBikes,
]
