import type { Testimonial } from '@/types/testimonial'

export const testimonials: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Emmanuel Okafor',
    country: 'Nigeria',
    rating: 5,
    text: 'I was skeptical about buying a vehicle from Germany without seeing it in person. RosM Autos sent a 47-photo inspection report before I paid. The Toyota Hilux arrived at Apapa Port in Lagos in 32 days — exactly the condition shown in the photos. I have already placed a second order.',
    productType: 'Toyota Hilux',
    imageAlt: 'Emmanuel Okafor, satisfied customer from Nigeria who purchased a Toyota Hilux',
  },
  {
    id: 'test-2',
    name: 'Carlos Mendes',
    country: 'Brazil',
    rating: 5,
    text: 'Bought a Massey Ferguson 4707 for my 200-hectare farm in Minas Gerais. The inspection report showed 1,840 engine hours and tested hydraulics — both matched perfectly on arrival. Their team walked me through Brazilian customs paperwork step by step. Saved me weeks of guesswork.',
    productType: 'Massey Ferguson Tractor',
    imageAlt: 'Carlos Mendes, satisfied customer from Brazil who purchased a Massey Ferguson tractor',
  },
  {
    id: 'test-3',
    name: 'Olena Kovalenko',
    country: 'Ukraine',
    rating: 5,
    text: 'We needed a Mercedes Sprinter for our delivery business in Odessa. RosM Autos handled the full export — from inspection in Lübbecke to port delivery in 14 days. Documentation was so thorough our customs broker cleared it in one day. We have ordered 3 more vans since.',
    productType: 'Mercedes Sprinter',
    imageAlt: 'Olena Kovalenko, satisfied customer from Ukraine who purchased a Mercedes Sprinter',
  },
  {
    id: 'test-4',
    name: 'Kwame Asante',
    country: 'Ghana',
    rating: 4,
    text: 'This was my second purchase — a Honda CR-V and a Toyota Corolla. Both arrived at Tema Port in the exact condition shown in the inspection reports. Their WhatsApp response time is under 2 hours. Pricing was 15–20% below what local importers in Accra quoted me.',
    productType: 'Honda CR-V',
    imageAlt: 'Kwame Asante, repeat customer from Ghana who purchased a Honda CR-V',
  },
  {
    id: 'test-5',
    name: 'Maria Fernanda Lopez',
    country: 'Colombia',
    rating: 5,
    text: 'Ordered a 750W cargo e-bike for last-mile deliveries in Bogota. The team confirmed battery health at 94% capacity and included the charger specs for Colombian outlets. Arrived via Buenaventura in 19 days — 6 days faster than quoted. Already using it daily.',
    productType: 'Electric City Bike',
    imageAlt: 'Maria Fernanda Lopez, customer from Colombia who purchased an electric bike',
  },
  {
    id: 'test-6',
    name: 'John Kamau',
    country: 'Kenya',
    rating: 5,
    text: 'As a fleet operator in Nairobi, I have purchased 12 vehicles from RosM Autos over 2 years — all delivered to Mombasa Port within the quoted timeframe. Every vehicle matched its inspection report. I have saved an estimated €18,000 compared to sourcing through local brokers. They are my only supplier now.',
    productType: 'Fleet Purchase - Various',
    imageAlt: 'John Kamau, fleet operator from Kenya and loyal RosM Autos customer',
  },
]
